# Copyright 2026 Dorsal Hub LTD
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import pytest
from jsonschema_rs import ValidationError as JsonSchemaValidationError
from dorsal_adapters.document.html_adapter.exporter import to_html


def test_to_html_col_layout_default(valid_document_record_1):
    """Test the default 'col' semantic flow layout."""
    result = to_html(valid_document_record_1, validate=False)

    assert "<!DOCTYPE html>" in result
    assert "Annual Report Summary" in result
    assert '<div class="layout-y">' in result
    assert '<div class="page-divider">Page 2</div>' in result

    assert 'class="page-container page-flow">' in result


def test_to_html_grid_layout():
    """Test the 2D 'grid' visual reconstruction layout."""

    record = {
        "extraction_type": "boxes",
        "unit": "px",
        "blocks": [
            {"text": "Col 1 Top", "box": {"x": 0, "y": 50, "width": 40, "height": 10}, "page_number": 1},
            {"text": "Col 1 Bottom", "box": {"x": 0, "y": 90, "width": 40, "height": 10}, "page_number": 1},
            {"text": "Col 2", "box": {"x": 50, "y": 50, "width": 40, "height": 50}, "page_number": 1},
        ],
    }

    result = to_html(record, validate=False, layout="grid")

    assert '<div class="layout-x">' in result
    assert "Col 1 Top" in result
    assert "Col 2" in result


def test_to_html_wireframe_layout(valid_document_record_1):
    """Test the absolute positioning 'wireframe' diagnostic layout."""
    result = to_html(valid_document_record_1, validate=False, layout="wireframe")

    assert "wireframe-box" in result
    assert "Annual Report Summary" not in result

    assert 'class="page-container page-wireframe" style="width:' in result


def test_to_html_empty_record():
    """Ensure empty records degrade gracefully."""
    result = to_html({"extraction_type": "text", "blocks": []}, validate=False)
    assert "No content extracted from this document." in result


def test_to_html_with_footer(valid_document_record_1):
    """Ensure raw HTML footers are safely injected at the bottom."""
    custom_footer = "<p>Generated by TestRunner</p>"
    result = to_html(valid_document_record_1, validate=False, footer=custom_footer)

    assert '<div class="document-footer">' in result
    assert custom_footer in result


def test_to_html_empty_with_footer():
    """Ensure footers are injected even if the document contains no extracted blocks."""
    custom_footer = "<footer>Empty Footer</footer>"
    result = to_html({"blocks": []}, validate=False, footer=custom_footer)

    assert "No content extracted" in result
    assert custom_footer in result


def test_to_html_custom_style_file(valid_document_record_1, tmp_path):
    """Test that the adapter can load and inject a custom user-provided CSS file."""
    custom_css_file = tmp_path / "my_custom_theme.css"
    custom_css_file.write_text("body { background-color: hotpink; }", encoding="utf-8")

    result = to_html(valid_document_record_1, validate=False, style=str(custom_css_file))
    assert "body { background-color: hotpink; }" in result


def test_to_html_invalid_style(valid_document_record_1):
    """Ensure invalid themes or missing files raise a descriptive error."""
    with pytest.raises(ValueError, match="neither a known theme .* nor a valid file path"):
        to_html(valid_document_record_1, validate=False, style="not_a_real_theme")


def test_to_html_invalid_layout(valid_document_record_1):
    """Ensure invalid layout strings immediately halt execution."""
    with pytest.raises(ValueError, match="Unknown layout: 'invalid_layout'"):
        to_html(valid_document_record_1, validate=False, layout="invalid_layout")


def test_to_html_validation_success(valid_document_record_1):
    """Verify that the strict validation flag allows compliant schemas to pass."""

    to_html(valid_document_record_1, validate=True)


def test_to_html_validation_failure(invalid_document_bad_norm):
    """Verify that validation correctly intercepts schema violations."""
    with pytest.raises(JsonSchemaValidationError):
        to_html(invalid_document_bad_norm, validate=True)


def test_to_html_col_missing_text(valid_document_record_2):
    """Ensure visual blocks (like logos) trigger the figure placeholder in 1D column mode."""

    result = to_html(valid_document_record_2, validate=False, layout="col")

    assert '<div class="figure-placeholder">[box]</div>' in result
    assert '<div class="figure-placeholder">[multi_polygon]</div>' in result


def test_to_html_fragment_true(valid_document_record_1):
    """Test that setting fragment=True omits the HTML shell and style blocks."""
    result = to_html(valid_document_record_1, validate=False, fragment=True)

    assert "<!DOCTYPE html>" not in result
    assert "<html" not in result
    assert "<head>" not in result
    assert "<style>" not in result
    assert "<body>" not in result
    assert "</body>" not in result
    assert "</html>" not in result

    assert "Annual Report Summary" in result
    assert '<div class="layout-y">' in result
    assert 'class="page-container page-flow">' in result


def test_to_html_fragment_empty():
    """Ensure empty records work properly in fragment mode."""
    result = to_html({"extraction_type": "text", "blocks": []}, validate=False, fragment=True)

    assert "<!DOCTYPE html>" not in result
    assert "<body>" not in result

    assert "No content extracted from this document." in result


def test_to_html_fragment_with_footer(valid_document_record_1):
    """Ensure footers are appended correctly when rendering as a fragment."""
    custom_footer = "<p>My Fragment Footer</p>"
    result = to_html(valid_document_record_1, validate=False, fragment=True, footer=custom_footer)

    assert "<body>" not in result
    assert "</html>" not in result

    assert '<div class="document-footer">' in result
    assert custom_footer in result
