# Copyright 2026 Dorsal Hub LTD
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import re
from typing import Any, Dict
from dorsal_adapters.common.validation import validate_record


def _format_time(seconds: float, include_milliseconds: bool = False) -> str:
    """Formats an arbitrary duration into a clean timestamp, safely supporting >24 hours."""
    m, s = divmod(seconds, 60)
    h, m = divmod(m, 60)

    if include_milliseconds:
        if h > 0:
            return f"{int(h):02d}:{int(m):02d}:{s:06.3f}"
        return f"{int(m):02d}:{s:06.3f}"
    else:
        if h > 0:
            return f"{int(h):02d}:{int(m):02d}:{int(s):02d}"
        return f"{int(m):02d}:{int(s):02d}"


def _parse_time(time_str: str) -> float:
    """Parses HH:MM:SS, MM:SS, or their decimal equivalents back into seconds."""
    parts = time_str.split(":")
    if len(parts) == 3:
        return int(parts[0]) * 3600 + int(parts[1]) * 60 + float(parts[2])
    elif len(parts) == 2:
        return int(parts[0]) * 60 + float(parts[1])
    return float(parts[0])


def to_md(
    record: Dict[str, Any],
    *,
    validate: bool = True,
    schema_version: str | None = None,
    include_timestamps: bool = True,
    include_milliseconds: bool = False,
    include_speakers: bool = False,
) -> str:
    """Egress: Converts an 'audio-transcription' record into a Markdown document optimized for RAG."""
    if validate:
        validate_record(record, schema_id="audio-transcription", version=schema_version)

    segments = record.get("segments", [])
    if not segments:
        text = record.get("text", "").strip()
        if not text:
            raise ValueError("The provided record contains no 'text' or 'segments'.")
        return f"# Transcription\n\n{text}"

    lines = ["# Transcription\n"]

    for segment in segments:
        line_parts = []

        if include_timestamps:
            start = _format_time(segment["start_time"], include_milliseconds)
            end = _format_time(segment["end_time"], include_milliseconds)
            line_parts.append(f"**[{start} - {end}]**")

        if include_speakers:
            speaker_name = segment.get("speaker", {}).get("name")
            if speaker_name:
                line_parts.append(f"**{speaker_name}:**")

        # Combine prefix elements and the text
        prefix = " ".join(line_parts)
        text = segment["text"].strip()

        if prefix:
            lines.append(f"{prefix} {text}")
        else:
            lines.append(text)

    return "\n\n".join(lines)


def from_md(
    md_content: str, producer: str = "md-adapter", *, validate: bool = True, schema_version: str | None = None
) -> Dict[str, Any]:
    """
    Ingress: Attempts to parse a Markdown string back into an 'audio-transcription' record.
    Note: Markdown is inherently lossy. This parser specifically looks for the format
    generated by `to_md`.
    """
    if not md_content.strip():
        raise ValueError("Provided Markdown content is empty.")

    segments = []
    full_text_blocks = []

    # Regex to match: **[00:00 - 00:05]** **Speaker:** Text OR **[00:00 - 00:05]** Text
    # It safely ignores the speaker part if it doesn't exist.
    pattern = re.compile(r"^\*\*\[([\d:]+)\s*-\s*([\d:]+)\]\*\*(?:\s*\*\*([^:]+):\*\*)?\s+(.*)", re.IGNORECASE)

    for line in md_content.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue

        match = pattern.match(line)
        if match:
            start_str, end_str, speaker_name, text = match.groups()

            segment = {"start_time": _parse_time(start_str), "end_time": _parse_time(end_str), "text": text.strip()}
            if speaker_name:
                segment["speaker"] = {"id": speaker_name.strip(), "name": speaker_name.strip()}

            segments.append(segment)
            full_text_blocks.append(text.strip())
        else:
            # If it doesn't match our strict timestamp format, treat the line as pure text without time data.
            # We assign a default 0.0 time just to satisfy the schema requirement if segments are used.
            clean_text = line.replace("**", "").strip()
            segments.append({"start_time": 0.0, "end_time": 0.0, "text": clean_text})
            full_text_blocks.append(clean_text)

    record = {
        "producer": producer,
        "text": " ".join(full_text_blocks),
        "segments": segments,
    }

    if validate:
        validate_record(record, schema_id="audio-transcription", version=schema_version)

    return record
