# Copyright 2026 Dorsal Hub LTD
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import json
import re
from typing import Any, Dict
from dorsal_adapters.common.validation import validate_record


def _format_time(seconds: float, include_milliseconds: bool = False) -> str:
    """Formats an arbitrary duration into a clean timestamp, safely supporting >24 hours."""
    m, s = divmod(seconds, 60)
    h, m = divmod(m, 60)

    if include_milliseconds:
        if h > 0:
            return f"{int(h):02d}:{int(m):02d}:{s:06.3f}"
        return f"{int(m):02d}:{s:06.3f}"
    else:
        if h > 0:
            return f"{int(h):02d}:{int(m):02d}:{int(s):02d}"
        return f"{int(m):02d}:{int(s):02d}"


def _parse_time(time_str: str) -> float:
    """Parses HH:MM:SS, MM:SS, or their decimal equivalents back into seconds."""
    parts = time_str.split(":")
    if len(parts) == 3:
        return int(parts[0]) * 3600 + int(parts[1]) * 60 + float(parts[2])
    elif len(parts) == 2:
        return int(parts[0]) * 60 + float(parts[1])
    return float(parts[0])


def to_md(
    record: Dict[str, Any],
    *,
    validate: bool = True,
    schema_version: str | None = None,
    include_timestamps: bool = True,
    include_milliseconds: bool = False,
    include_speakers: bool = False,
    include_frontmatter: bool = True,
    low_confidence_threshold: float = 0.80,
) -> str:
    """Egress: Converts an 'audio-transcription' record into a Markdown document optimized for RAG."""
    if validate:
        validate_record(record, schema_id="audio-transcription", version=schema_version)

    output = []

    if include_frontmatter:
        frontmatter = ["---"]
        for key in ["producer", "language", "duration", "score_explanation", "track_id"]:
            if key in record:
                frontmatter.append(f"{key}: {record[key]}")

        if "attributes" in record and isinstance(record["attributes"], dict):
            frontmatter.append("attributes:")
            for k, v in record["attributes"].items():
                val_str = json.dumps(v)
                frontmatter.append(f"  {k}: {val_str}")

        frontmatter.append("---")
        if len(frontmatter) > 2:
            output.append("\n".join(frontmatter))

    segments = record.get("segments", [])
    if not segments:
        text = record.get("text", "").strip()
        if not text:
            raise ValueError("The provided record contains no 'text' or 'segments'.")
        output.append("# Transcription")
        output.append(text)
        return "\n\n".join(output)

    output.append("# Transcription")

    for segment in segments:
        line_parts = []

        if include_timestamps:
            start = _format_time(segment["start_time"], include_milliseconds)
            end = _format_time(segment["end_time"], include_milliseconds)
            line_parts.append(f"**[{start} - {end}]**")

        if include_speakers:
            speaker_name = segment.get("speaker", {}).get("name")
            if speaker_name:
                line_parts.append(f"**{speaker_name}:**")

        prefix = " ".join(line_parts)
        text = segment.get("text", "").strip()
        score = segment.get("score")
        events = segment.get("events", [])

        if events:
            event_str = ", ".join(events)
            output.append(f"> *[{event_str}]*")

        if not text:
            continue

        if score is not None and score < low_confidence_threshold:
            if prefix:
                output.append(f"> ⚠️ **Low Confidence Read ({score:.2f})**:\n> {prefix} {text}")
            else:
                output.append(f"> ⚠️ **Low Confidence Read ({score:.2f})**:\n> {text}")
        else:
            if prefix:
                output.append(f"{prefix} {text}")
            else:
                output.append(text)

    return "\n\n".join(output)


def from_md(
    md_content: str, producer: str = "md-adapter", *, validate: bool = True, schema_version: str | None = None
) -> Dict[str, Any]:
    """
    Ingress: Attempts to parse a Markdown string back into an 'audio-transcription' record.
    Note: Markdown is inherently lossy. This parser specifically looks for the format
    generated by `to_md`.
    """
    if not md_content.strip():
        raise ValueError("Provided Markdown content is empty.")

    clean_content = re.sub(r"^---\n.*?\n---\n", "", md_content, flags=re.DOTALL).strip()

    segments = []
    full_text_blocks = []

    pattern = re.compile(r"^\*\*\[([\d:]+)\s*-\s*([\d:]+)\]\*\*(?:\s*\*\*([^:]+):\*\*)?\s+(.*)", re.IGNORECASE)

    for line in clean_content.splitlines():
        line = line.strip()

        if not line or line.startswith("#") or line.startswith("> ⚠️"):
            continue

        line = re.sub(r"^>\s*", "", line).strip()

        event_match = re.match(r"^\*\[(.*)\]\*$", line)
        if event_match:
            events = [e.strip() for e in event_match.group(1).split(",")]
            segments.append({"start_time": 0.0, "end_time": 0.0, "text": "", "events": events})
            continue

        match = pattern.match(line)
        if match:
            start_str, end_str, speaker_name, text = match.groups()

            segment = {"start_time": _parse_time(start_str), "end_time": _parse_time(end_str), "text": text.strip()}
            if speaker_name:
                segment["speaker"] = {"id": speaker_name.strip(), "name": speaker_name.strip()}

            segments.append(segment)
            full_text_blocks.append(text.strip())
        else:
            clean_text = line.replace("**", "").strip()
            segments.append({"start_time": 0.0, "end_time": 0.0, "text": clean_text})
            full_text_blocks.append(clean_text)

    clean_text_blocks = [t for t in full_text_blocks if t]

    record = {
        "producer": producer,
        "text": " ".join(clean_text_blocks),
        "segments": segments,
    }

    if validate:
        validate_record(record, schema_id="audio-transcription", version=schema_version)

    return record
